// Copyright (C) 2012-2015 Institute of Energy Efficient Building E3D,
// RWTH Aachen University, Germany.
//
// This program was developed for the EnEff-BIM project. In EnEff-BIM, 
// a project participating in IEA Annex 60, translators between Building 
// Information Models (BIM) and Modelica are developed to support building
// and community energy performance simulation. This is accomplished through 
// extending existing standards for exchanging energy calculation data, and 
// through data representation formats such as the Industry Foundation Classes (IFC).
//
// This program is free software; you can redistribute it and/or modify it 
// under the terms of the GNU General Public License version 2 as published 
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, simmodel2c++ gives permission to 
// link this program with the XML data binding framework generated by the 
// Code Synthesis Tools CC, and distribute linked combinations including 
// the two. You must obey the GNU General Public License version 2 in all 
// respects for all of the code used. If you modify this copy of the program, 
// you may extend this exception to your version of the program, but you are 
// not obligated to do so. If you do not wish to do so, delete this exception 
// statement from your version.
//

#ifndef INCLUDE_FILES_H
#define INCLUDE_FILES_H

//#include <Python.h>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <vector>
#include <list>
#include <set>
#include <string>
#include <QString>
#include <QMetaType>
#include <QMetaMethod>
#include <QMetaObject>
// include SimModel
#include "../simmodel_framework/simmodel.hxx"
// include SimModel mapping rules
#include "../mapping_rule_framework/datamap.hxx"

// refer to the SimModel class API
typedef namespaces::Sim::Model::SimModel SimModel;
// refer to the mapping rule class API
typedef namespaces::Sim::DataMap::Data_Model_Map SimMap;
// load XML schema type
using xml_schema::idrefs;
using xml_schema::idref;
using namespaces::Sim::SimModelCore::doubleList;
// using IO API
using namespace std;

typedef idrefs::iterator idrefs_it;
typedef idrefs::iterator idrefs_iterator;
typedef namespaces::Sim::SimModelCore::doubleList::iterator doubleList_it;

#endif