// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SimGeomCurve_CompositeCurveSegment.hxx"

namespace schema
{
  namespace simxml
  {
    namespace ResourcesGeometry
    {
      // SimGeomCurve_CompositeCurveSegment
      // 

      const SimGeomCurve_CompositeCurveSegment::Transition_optional& SimGeomCurve_CompositeCurveSegment::
      Transition () const
      {
        return this->Transition_;
      }

      SimGeomCurve_CompositeCurveSegment::Transition_optional& SimGeomCurve_CompositeCurveSegment::
      Transition ()
      {
        return this->Transition_;
      }

      void SimGeomCurve_CompositeCurveSegment::
      Transition (const Transition_type& x)
      {
        this->Transition_.set (x);
      }

      void SimGeomCurve_CompositeCurveSegment::
      Transition (const Transition_optional& x)
      {
        this->Transition_ = x;
      }

      void SimGeomCurve_CompositeCurveSegment::
      Transition (::std::auto_ptr< Transition_type > x)
      {
        this->Transition_.set (x);
      }

      const SimGeomCurve_CompositeCurveSegment::SameSense_optional& SimGeomCurve_CompositeCurveSegment::
      SameSense () const
      {
        return this->SameSense_;
      }

      SimGeomCurve_CompositeCurveSegment::SameSense_optional& SimGeomCurve_CompositeCurveSegment::
      SameSense ()
      {
        return this->SameSense_;
      }

      void SimGeomCurve_CompositeCurveSegment::
      SameSense (const SameSense_type& x)
      {
        this->SameSense_.set (x);
      }

      void SimGeomCurve_CompositeCurveSegment::
      SameSense (const SameSense_optional& x)
      {
        this->SameSense_ = x;
      }

      const SimGeomCurve_CompositeCurveSegment::ParentCurve_optional& SimGeomCurve_CompositeCurveSegment::
      ParentCurve () const
      {
        return this->ParentCurve_;
      }

      SimGeomCurve_CompositeCurveSegment::ParentCurve_optional& SimGeomCurve_CompositeCurveSegment::
      ParentCurve ()
      {
        return this->ParentCurve_;
      }

      void SimGeomCurve_CompositeCurveSegment::
      ParentCurve (const ParentCurve_type& x)
      {
        this->ParentCurve_.set (x);
      }

      void SimGeomCurve_CompositeCurveSegment::
      ParentCurve (const ParentCurve_optional& x)
      {
        this->ParentCurve_ = x;
      }

      void SimGeomCurve_CompositeCurveSegment::
      ParentCurve (::std::auto_ptr< ParentCurve_type > x)
      {
        this->ParentCurve_.set (x);
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace schema
{
  namespace simxml
  {
    namespace ResourcesGeometry
    {
      // SimGeomCurve_CompositeCurveSegment
      //

      SimGeomCurve_CompositeCurveSegment::
      SimGeomCurve_CompositeCurveSegment ()
      : ::schema::simxml::ResourcesGeometry::SimGeomCurve (),
        Transition_ (this),
        SameSense_ (this),
        ParentCurve_ (this)
      {
      }

      SimGeomCurve_CompositeCurveSegment::
      SimGeomCurve_CompositeCurveSegment (const RefId_type& RefId)
      : ::schema::simxml::ResourcesGeometry::SimGeomCurve (RefId),
        Transition_ (this),
        SameSense_ (this),
        ParentCurve_ (this)
      {
      }

      SimGeomCurve_CompositeCurveSegment::
      SimGeomCurve_CompositeCurveSegment (const SimGeomCurve_CompositeCurveSegment& x,
                                          ::xml_schema::flags f,
                                          ::xml_schema::container* c)
      : ::schema::simxml::ResourcesGeometry::SimGeomCurve (x, f, c),
        Transition_ (x.Transition_, f, this),
        SameSense_ (x.SameSense_, f, this),
        ParentCurve_ (x.ParentCurve_, f, this)
      {
      }

      SimGeomCurve_CompositeCurveSegment::
      SimGeomCurve_CompositeCurveSegment (const ::xercesc::DOMElement& e,
                                          ::xml_schema::flags f,
                                          ::xml_schema::container* c)
      : ::schema::simxml::ResourcesGeometry::SimGeomCurve (e, f | ::xml_schema::flags::base, c),
        Transition_ (this),
        SameSense_ (this),
        ParentCurve_ (this)
      {
        if ((f & ::xml_schema::flags::base) == 0)
        {
          ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
          this->parse (p, f);
        }
      }

      void SimGeomCurve_CompositeCurveSegment::
      parse (::xsd::cxx::xml::dom::parser< char >& p,
             ::xml_schema::flags f)
      {
        this->::schema::simxml::ResourcesGeometry::SimGeomCurve::parse (p, f);

        for (; p.more_content (); p.next_content (false))
        {
          const ::xercesc::DOMElement& i (p.cur_element ());
          const ::xsd::cxx::xml::qualified_name< char > n (
            ::xsd::cxx::xml::dom::name< char > (i));

          // Transition
          //
          if (n.name () == "Transition" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            ::std::auto_ptr< Transition_type > r (
              Transition_traits::create (i, f, this));

            if (!this->Transition_)
            {
              this->Transition_.set (r);
              continue;
            }
          }

          // SameSense
          //
          if (n.name () == "SameSense" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            if (!this->SameSense_)
            {
              this->SameSense_.set (SameSense_traits::create (i, f, this));
              continue;
            }
          }

          // ParentCurve
          //
          if (n.name () == "ParentCurve" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            ::std::auto_ptr< ParentCurve_type > r (
              ParentCurve_traits::create (i, f, this));

            if (!this->ParentCurve_)
            {
              this->ParentCurve_.set (r);
              continue;
            }
          }

          break;
        }
      }

      SimGeomCurve_CompositeCurveSegment* SimGeomCurve_CompositeCurveSegment::
      _clone (::xml_schema::flags f,
              ::xml_schema::container* c) const
      {
        return new class SimGeomCurve_CompositeCurveSegment (*this, f, c);
      }

      SimGeomCurve_CompositeCurveSegment& SimGeomCurve_CompositeCurveSegment::
      operator= (const SimGeomCurve_CompositeCurveSegment& x)
      {
        if (this != &x)
        {
          static_cast< ::schema::simxml::ResourcesGeometry::SimGeomCurve& > (*this) = x;
          this->Transition_ = x.Transition_;
          this->SameSense_ = x.SameSense_;
          this->ParentCurve_ = x.ParentCurve_;
        }

        return *this;
      }

      SimGeomCurve_CompositeCurveSegment::
      ~SimGeomCurve_CompositeCurveSegment ()
      {
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace schema
{
  namespace simxml
  {
    namespace ResourcesGeometry
    {
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

