// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SimResourceObject.hxx"

#include "selectedpropertygroups.hxx"

namespace schema
{
  namespace simxml
  {
    namespace SimModelCore
    {
      // SimResourceObject
      // 

      const SimResourceObject::AssignedToGroups_optional& SimResourceObject::
      AssignedToGroups () const
      {
        return this->AssignedToGroups_;
      }

      SimResourceObject::AssignedToGroups_optional& SimResourceObject::
      AssignedToGroups ()
      {
        return this->AssignedToGroups_;
      }

      void SimResourceObject::
      AssignedToGroups (const AssignedToGroups_type& x)
      {
        this->AssignedToGroups_.set (x);
      }

      void SimResourceObject::
      AssignedToGroups (const AssignedToGroups_optional& x)
      {
        this->AssignedToGroups_ = x;
      }

      void SimResourceObject::
      AssignedToGroups (::std::auto_ptr< AssignedToGroups_type > x)
      {
        this->AssignedToGroups_.set (x);
      }

      const SimResourceObject::SelectedPropertyGroups_optional& SimResourceObject::
      SelectedPropertyGroups () const
      {
        return this->SelectedPropertyGroups_;
      }

      SimResourceObject::SelectedPropertyGroups_optional& SimResourceObject::
      SelectedPropertyGroups ()
      {
        return this->SelectedPropertyGroups_;
      }

      void SimResourceObject::
      SelectedPropertyGroups (const SelectedPropertyGroups_type& x)
      {
        this->SelectedPropertyGroups_.set (x);
      }

      void SimResourceObject::
      SelectedPropertyGroups (const SelectedPropertyGroups_optional& x)
      {
        this->SelectedPropertyGroups_ = x;
      }

      void SimResourceObject::
      SelectedPropertyGroups (::std::auto_ptr< SelectedPropertyGroups_type > x)
      {
        this->SelectedPropertyGroups_.set (x);
      }

      const SimResourceObject::IsTemplateObject_optional& SimResourceObject::
      IsTemplateObject () const
      {
        return this->IsTemplateObject_;
      }

      SimResourceObject::IsTemplateObject_optional& SimResourceObject::
      IsTemplateObject ()
      {
        return this->IsTemplateObject_;
      }

      void SimResourceObject::
      IsTemplateObject (const IsTemplateObject_type& x)
      {
        this->IsTemplateObject_.set (x);
      }

      void SimResourceObject::
      IsTemplateObject (const IsTemplateObject_optional& x)
      {
        this->IsTemplateObject_ = x;
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace schema
{
  namespace simxml
  {
    namespace SimModelCore
    {
      // SimResourceObject
      //

      SimResourceObject::
      SimResourceObject ()
      : ::schema::simxml::SimModelCore::SimRoot (),
        AssignedToGroups_ (this),
        SelectedPropertyGroups_ (this),
        IsTemplateObject_ (this)
      {
      }

      SimResourceObject::
      SimResourceObject (const RefId_type& RefId)
      : ::schema::simxml::SimModelCore::SimRoot (RefId),
        AssignedToGroups_ (this),
        SelectedPropertyGroups_ (this),
        IsTemplateObject_ (this)
      {
      }

      SimResourceObject::
      SimResourceObject (const SimResourceObject& x,
                         ::xml_schema::flags f,
                         ::xml_schema::container* c)
      : ::schema::simxml::SimModelCore::SimRoot (x, f, c),
        AssignedToGroups_ (x.AssignedToGroups_, f, this),
        SelectedPropertyGroups_ (x.SelectedPropertyGroups_, f, this),
        IsTemplateObject_ (x.IsTemplateObject_, f, this)
      {
      }

      SimResourceObject::
      SimResourceObject (const ::xercesc::DOMElement& e,
                         ::xml_schema::flags f,
                         ::xml_schema::container* c)
      : ::schema::simxml::SimModelCore::SimRoot (e, f | ::xml_schema::flags::base, c),
        AssignedToGroups_ (this),
        SelectedPropertyGroups_ (this),
        IsTemplateObject_ (this)
      {
        if ((f & ::xml_schema::flags::base) == 0)
        {
          ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
          this->parse (p, f);
        }
      }

      void SimResourceObject::
      parse (::xsd::cxx::xml::dom::parser< char >& p,
             ::xml_schema::flags f)
      {
        this->::schema::simxml::SimModelCore::SimRoot::parse (p, f);

        for (; p.more_content (); p.next_content (false))
        {
          const ::xercesc::DOMElement& i (p.cur_element ());
          const ::xsd::cxx::xml::qualified_name< char > n (
            ::xsd::cxx::xml::dom::name< char > (i));

          // AssignedToGroups
          //
          if (n.name () == "AssignedToGroups" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/SimModelCore")
          {
            ::std::auto_ptr< AssignedToGroups_type > r (
              AssignedToGroups_traits::create (i, f, this));

            if (!this->AssignedToGroups_)
            {
              this->AssignedToGroups_.set (r);
              continue;
            }
          }

          // SelectedPropertyGroups
          //
          if (n.name () == "SelectedPropertyGroups" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/SimModelCore")
          {
            ::std::auto_ptr< SelectedPropertyGroups_type > r (
              SelectedPropertyGroups_traits::create (i, f, this));

            if (!this->SelectedPropertyGroups_)
            {
              this->SelectedPropertyGroups_.set (r);
              continue;
            }
          }

          // IsTemplateObject
          //
          if (n.name () == "IsTemplateObject" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/SimModelCore")
          {
            if (!this->IsTemplateObject_)
            {
              this->IsTemplateObject_.set (IsTemplateObject_traits::create (i, f, this));
              continue;
            }
          }

          break;
        }
      }

      SimResourceObject* SimResourceObject::
      _clone (::xml_schema::flags f,
              ::xml_schema::container* c) const
      {
        return new class SimResourceObject (*this, f, c);
      }

      SimResourceObject& SimResourceObject::
      operator= (const SimResourceObject& x)
      {
        if (this != &x)
        {
          static_cast< ::schema::simxml::SimModelCore::SimRoot& > (*this) = x;
          this->AssignedToGroups_ = x.AssignedToGroups_;
          this->SelectedPropertyGroups_ = x.SelectedPropertyGroups_;
          this->IsTemplateObject_ = x.IsTemplateObject_;
        }

        return *this;
      }

      SimResourceObject::
      ~SimResourceObject ()
      {
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace schema
{
  namespace simxml
  {
    namespace SimModelCore
    {
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

