// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SimFlowTerminal.hxx"

namespace schema
{
  namespace simxml
  {
    namespace MepModel
    {
      // SimFlowTerminal
      // 

      const SimFlowTerminal::Name_optional& SimFlowTerminal::
      Name () const
      {
        return this->Name_;
      }

      SimFlowTerminal::Name_optional& SimFlowTerminal::
      Name ()
      {
        return this->Name_;
      }

      void SimFlowTerminal::
      Name (const Name_type& x)
      {
        this->Name_.set (x);
      }

      void SimFlowTerminal::
      Name (const Name_optional& x)
      {
        this->Name_ = x;
      }

      void SimFlowTerminal::
      Name (::std::auto_ptr< Name_type > x)
      {
        this->Name_.set (x);
      }

      const SimFlowTerminal::Representation_optional& SimFlowTerminal::
      Representation () const
      {
        return this->Representation_;
      }

      SimFlowTerminal::Representation_optional& SimFlowTerminal::
      Representation ()
      {
        return this->Representation_;
      }

      void SimFlowTerminal::
      Representation (const Representation_type& x)
      {
        this->Representation_.set (x);
      }

      void SimFlowTerminal::
      Representation (const Representation_optional& x)
      {
        this->Representation_ = x;
      }

      void SimFlowTerminal::
      Representation (::std::auto_ptr< Representation_type > x)
      {
        this->Representation_.set (x);
      }

      const SimFlowTerminal::InteriorOrExterior_optional& SimFlowTerminal::
      InteriorOrExterior () const
      {
        return this->InteriorOrExterior_;
      }

      SimFlowTerminal::InteriorOrExterior_optional& SimFlowTerminal::
      InteriorOrExterior ()
      {
        return this->InteriorOrExterior_;
      }

      void SimFlowTerminal::
      InteriorOrExterior (const InteriorOrExterior_type& x)
      {
        this->InteriorOrExterior_.set (x);
      }

      void SimFlowTerminal::
      InteriorOrExterior (const InteriorOrExterior_optional& x)
      {
        this->InteriorOrExterior_ = x;
      }

      void SimFlowTerminal::
      InteriorOrExterior (::std::auto_ptr< InteriorOrExterior_type > x)
      {
        this->InteriorOrExterior_.set (x);
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace schema
{
  namespace simxml
  {
    namespace MepModel
    {
      // SimFlowTerminal
      //

      SimFlowTerminal::
      SimFlowTerminal ()
      : ::schema::simxml::SimModelCore::SimDistributionFlowElement (),
        Name_ (this),
        Representation_ (this),
        InteriorOrExterior_ (this)
      {
      }

      SimFlowTerminal::
      SimFlowTerminal (const RefId_type& RefId)
      : ::schema::simxml::SimModelCore::SimDistributionFlowElement (RefId),
        Name_ (this),
        Representation_ (this),
        InteriorOrExterior_ (this)
      {
      }

      SimFlowTerminal::
      SimFlowTerminal (const SimFlowTerminal& x,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
      : ::schema::simxml::SimModelCore::SimDistributionFlowElement (x, f, c),
        Name_ (x.Name_, f, this),
        Representation_ (x.Representation_, f, this),
        InteriorOrExterior_ (x.InteriorOrExterior_, f, this)
      {
      }

      SimFlowTerminal::
      SimFlowTerminal (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
      : ::schema::simxml::SimModelCore::SimDistributionFlowElement (e, f | ::xml_schema::flags::base, c),
        Name_ (this),
        Representation_ (this),
        InteriorOrExterior_ (this)
      {
        if ((f & ::xml_schema::flags::base) == 0)
        {
          ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
          this->parse (p, f);
        }
      }

      void SimFlowTerminal::
      parse (::xsd::cxx::xml::dom::parser< char >& p,
             ::xml_schema::flags f)
      {
        this->::schema::simxml::SimModelCore::SimDistributionFlowElement::parse (p, f);

        for (; p.more_content (); p.next_content (false))
        {
          const ::xercesc::DOMElement& i (p.cur_element ());
          const ::xsd::cxx::xml::qualified_name< char > n (
            ::xsd::cxx::xml::dom::name< char > (i));

          // Name
          //
          if (n.name () == "Name" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/MepModel")
          {
            ::std::auto_ptr< Name_type > r (
              Name_traits::create (i, f, this));

            if (!this->Name_)
            {
              this->Name_.set (r);
              continue;
            }
          }

          // Representation
          //
          if (n.name () == "Representation" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/MepModel")
          {
            ::std::auto_ptr< Representation_type > r (
              Representation_traits::create (i, f, this));

            if (!this->Representation_)
            {
              this->Representation_.set (r);
              continue;
            }
          }

          // InteriorOrExterior
          //
          if (n.name () == "InteriorOrExterior" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/MepModel")
          {
            ::std::auto_ptr< InteriorOrExterior_type > r (
              InteriorOrExterior_traits::create (i, f, this));

            if (!this->InteriorOrExterior_)
            {
              this->InteriorOrExterior_.set (r);
              continue;
            }
          }

          break;
        }
      }

      SimFlowTerminal* SimFlowTerminal::
      _clone (::xml_schema::flags f,
              ::xml_schema::container* c) const
      {
        return new class SimFlowTerminal (*this, f, c);
      }

      SimFlowTerminal& SimFlowTerminal::
      operator= (const SimFlowTerminal& x)
      {
        if (this != &x)
        {
          static_cast< ::schema::simxml::SimModelCore::SimDistributionFlowElement& > (*this) = x;
          this->Name_ = x.Name_;
          this->Representation_ = x.Representation_;
          this->InteriorOrExterior_ = x.InteriorOrExterior_;
        }

        return *this;
      }

      SimFlowTerminal::
      ~SimFlowTerminal ()
      {
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace schema
{
  namespace simxml
  {
    namespace MepModel
    {
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

