// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SimCost_Default.hxx"

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
      // SimCost_Default
      // 

      const SimCost_Default::GlobalId_optional& SimCost_Default::
      GlobalId () const
      {
        return this->GlobalId_;
      }

      SimCost_Default::GlobalId_optional& SimCost_Default::
      GlobalId ()
      {
        return this->GlobalId_;
      }

      void SimCost_Default::
      GlobalId (const GlobalId_type& x)
      {
        this->GlobalId_.set (x);
      }

      void SimCost_Default::
      GlobalId (const GlobalId_optional& x)
      {
        this->GlobalId_ = x;
      }

      void SimCost_Default::
      GlobalId (::std::auto_ptr< GlobalId_type > x)
      {
        this->GlobalId_.set (x);
      }

      const SimCost_Default::OwnerHistory_optional& SimCost_Default::
      OwnerHistory () const
      {
        return this->OwnerHistory_;
      }

      SimCost_Default::OwnerHistory_optional& SimCost_Default::
      OwnerHistory ()
      {
        return this->OwnerHistory_;
      }

      void SimCost_Default::
      OwnerHistory (const OwnerHistory_type& x)
      {
        this->OwnerHistory_.set (x);
      }

      void SimCost_Default::
      OwnerHistory (const OwnerHistory_optional& x)
      {
        this->OwnerHistory_ = x;
      }

      void SimCost_Default::
      OwnerHistory (::std::auto_ptr< OwnerHistory_type > x)
      {
        this->OwnerHistory_.set (x);
      }

      const SimCost_Default::Name_optional& SimCost_Default::
      Name () const
      {
        return this->Name_;
      }

      SimCost_Default::Name_optional& SimCost_Default::
      Name ()
      {
        return this->Name_;
      }

      void SimCost_Default::
      Name (const Name_type& x)
      {
        this->Name_.set (x);
      }

      void SimCost_Default::
      Name (const Name_optional& x)
      {
        this->Name_ = x;
      }

      void SimCost_Default::
      Name (::std::auto_ptr< Name_type > x)
      {
        this->Name_.set (x);
      }

      const SimCost_Default::ObjectType_optional& SimCost_Default::
      ObjectType () const
      {
        return this->ObjectType_;
      }

      SimCost_Default::ObjectType_optional& SimCost_Default::
      ObjectType ()
      {
        return this->ObjectType_;
      }

      void SimCost_Default::
      ObjectType (const ObjectType_type& x)
      {
        this->ObjectType_.set (x);
      }

      void SimCost_Default::
      ObjectType (const ObjectType_optional& x)
      {
        this->ObjectType_ = x;
      }

      void SimCost_Default::
      ObjectType (::std::auto_ptr< ObjectType_type > x)
      {
        this->ObjectType_.set (x);
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
      // SimCost_Default
      //

      SimCost_Default::
      SimCost_Default (const RefId_type& RefId)
      : ::namespaces::Sim::ResourcesGeneral::SimCost (RefId),
        GlobalId_ (this),
        OwnerHistory_ (this),
        Name_ (this),
        ObjectType_ (this)
      {
      }

      SimCost_Default::
      SimCost_Default (const SimCost_Default& x,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
      : ::namespaces::Sim::ResourcesGeneral::SimCost (x, f, c),
        GlobalId_ (x.GlobalId_, f, this),
        OwnerHistory_ (x.OwnerHistory_, f, this),
        Name_ (x.Name_, f, this),
        ObjectType_ (x.ObjectType_, f, this)
      {
      }

      SimCost_Default::
      SimCost_Default (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
      : ::namespaces::Sim::ResourcesGeneral::SimCost (e, f | ::xml_schema::flags::base, c),
        GlobalId_ (this),
        OwnerHistory_ (this),
        Name_ (this),
        ObjectType_ (this)
      {
        if ((f & ::xml_schema::flags::base) == 0)
        {
          ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
          this->parse (p, f);
        }
      }

      void SimCost_Default::
      parse (::xsd::cxx::xml::dom::parser< char >& p,
             ::xml_schema::flags f)
      {
        this->::namespaces::Sim::ResourcesGeneral::SimCost::parse (p, f);

        for (; p.more_content (); p.next_content (false))
        {
          const ::xercesc::DOMElement& i (p.cur_element ());
          const ::xsd::cxx::xml::qualified_name< char > n (
            ::xsd::cxx::xml::dom::name< char > (i));

          // GlobalId
          //
          if (n.name () == "GlobalId" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< GlobalId_type > r (
              GlobalId_traits::create (i, f, this));

            if (!this->GlobalId_)
            {
              this->GlobalId_.set (r);
              continue;
            }
          }

          // OwnerHistory
          //
          if (n.name () == "OwnerHistory" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< OwnerHistory_type > r (
              OwnerHistory_traits::create (i, f, this));

            if (!this->OwnerHistory_)
            {
              this->OwnerHistory_.set (r);
              continue;
            }
          }

          // Name
          //
          if (n.name () == "Name" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< Name_type > r (
              Name_traits::create (i, f, this));

            if (!this->Name_)
            {
              this->Name_.set (r);
              continue;
            }
          }

          // ObjectType
          //
          if (n.name () == "ObjectType" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< ObjectType_type > r (
              ObjectType_traits::create (i, f, this));

            if (!this->ObjectType_)
            {
              this->ObjectType_.set (r);
              continue;
            }
          }

          break;
        }
      }

      SimCost_Default* SimCost_Default::
      _clone (::xml_schema::flags f,
              ::xml_schema::container* c) const
      {
        return new class SimCost_Default (*this, f, c);
      }

      SimCost_Default& SimCost_Default::
      operator= (const SimCost_Default& x)
      {
        if (this != &x)
        {
          static_cast< ::namespaces::Sim::ResourcesGeneral::SimCost& > (*this) = x;
          this->GlobalId_ = x.GlobalId_;
          this->OwnerHistory_ = x.OwnerHistory_;
          this->Name_ = x.Name_;
          this->ObjectType_ = x.ObjectType_;
        }

        return *this;
      }

      SimCost_Default::
      ~SimCost_Default ()
      {
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

