// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SimColumnParams.hxx"

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
      // SimColumnParams
      // 

      const SimColumnParams::XThickness_optional& SimColumnParams::
      XThickness () const
      {
        return this->XThickness_;
      }

      SimColumnParams::XThickness_optional& SimColumnParams::
      XThickness ()
      {
        return this->XThickness_;
      }

      void SimColumnParams::
      XThickness (const XThickness_type& x)
      {
        this->XThickness_.set (x);
      }

      void SimColumnParams::
      XThickness (const XThickness_optional& x)
      {
        this->XThickness_ = x;
      }

      const SimColumnParams::YThickness_optional& SimColumnParams::
      YThickness () const
      {
        return this->YThickness_;
      }

      SimColumnParams::YThickness_optional& SimColumnParams::
      YThickness ()
      {
        return this->YThickness_;
      }

      void SimColumnParams::
      YThickness (const YThickness_type& x)
      {
        this->YThickness_.set (x);
      }

      void SimColumnParams::
      YThickness (const YThickness_optional& x)
      {
        this->YThickness_ = x;
      }

      const SimColumnParams::Height_optional& SimColumnParams::
      Height () const
      {
        return this->Height_;
      }

      SimColumnParams::Height_optional& SimColumnParams::
      Height ()
      {
        return this->Height_;
      }

      void SimColumnParams::
      Height (const Height_type& x)
      {
        this->Height_.set (x);
      }

      void SimColumnParams::
      Height (const Height_optional& x)
      {
        this->Height_ = x;
      }

      const SimColumnParams::BaseElevation_optional& SimColumnParams::
      BaseElevation () const
      {
        return this->BaseElevation_;
      }

      SimColumnParams::BaseElevation_optional& SimColumnParams::
      BaseElevation ()
      {
        return this->BaseElevation_;
      }

      void SimColumnParams::
      BaseElevation (const BaseElevation_type& x)
      {
        this->BaseElevation_.set (x);
      }

      void SimColumnParams::
      BaseElevation (const BaseElevation_optional& x)
      {
        this->BaseElevation_ = x;
      }

      const SimColumnParams::DegreeOfNormal_optional& SimColumnParams::
      DegreeOfNormal () const
      {
        return this->DegreeOfNormal_;
      }

      SimColumnParams::DegreeOfNormal_optional& SimColumnParams::
      DegreeOfNormal ()
      {
        return this->DegreeOfNormal_;
      }

      void SimColumnParams::
      DegreeOfNormal (const DegreeOfNormal_type& x)
      {
        this->DegreeOfNormal_.set (x);
      }

      void SimColumnParams::
      DegreeOfNormal (const DegreeOfNormal_optional& x)
      {
        this->DegreeOfNormal_ = x;
      }

      const SimColumnParams::ProfilePath_optional& SimColumnParams::
      ProfilePath () const
      {
        return this->ProfilePath_;
      }

      SimColumnParams::ProfilePath_optional& SimColumnParams::
      ProfilePath ()
      {
        return this->ProfilePath_;
      }

      void SimColumnParams::
      ProfilePath (const ProfilePath_type& x)
      {
        this->ProfilePath_.set (x);
      }

      void SimColumnParams::
      ProfilePath (const ProfilePath_optional& x)
      {
        this->ProfilePath_ = x;
      }

      void SimColumnParams::
      ProfilePath (::std::auto_ptr< ProfilePath_type > x)
      {
        this->ProfilePath_.set (x);
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
      // SimColumnParams
      //

      SimColumnParams::
      SimColumnParams (const RefId_type& RefId)
      : ::namespaces::Sim::ResourcesGeneral::SimBldgModelParams (RefId),
        XThickness_ (this),
        YThickness_ (this),
        Height_ (this),
        BaseElevation_ (this),
        DegreeOfNormal_ (this),
        ProfilePath_ (this)
      {
      }

      SimColumnParams::
      SimColumnParams (const SimColumnParams& x,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
      : ::namespaces::Sim::ResourcesGeneral::SimBldgModelParams (x, f, c),
        XThickness_ (x.XThickness_, f, this),
        YThickness_ (x.YThickness_, f, this),
        Height_ (x.Height_, f, this),
        BaseElevation_ (x.BaseElevation_, f, this),
        DegreeOfNormal_ (x.DegreeOfNormal_, f, this),
        ProfilePath_ (x.ProfilePath_, f, this)
      {
      }

      SimColumnParams::
      SimColumnParams (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f,
                       ::xml_schema::container* c)
      : ::namespaces::Sim::ResourcesGeneral::SimBldgModelParams (e, f | ::xml_schema::flags::base, c),
        XThickness_ (this),
        YThickness_ (this),
        Height_ (this),
        BaseElevation_ (this),
        DegreeOfNormal_ (this),
        ProfilePath_ (this)
      {
        if ((f & ::xml_schema::flags::base) == 0)
        {
          ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
          this->parse (p, f);
        }
      }

      void SimColumnParams::
      parse (::xsd::cxx::xml::dom::parser< char >& p,
             ::xml_schema::flags f)
      {
        this->::namespaces::Sim::ResourcesGeneral::SimBldgModelParams::parse (p, f);

        for (; p.more_content (); p.next_content (false))
        {
          const ::xercesc::DOMElement& i (p.cur_element ());
          const ::xsd::cxx::xml::qualified_name< char > n (
            ::xsd::cxx::xml::dom::name< char > (i));

          // XThickness
          //
          if (n.name () == "XThickness" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            if (!this->XThickness_)
            {
              this->XThickness_.set (XThickness_traits::create (i, f, this));
              continue;
            }
          }

          // YThickness
          //
          if (n.name () == "YThickness" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            if (!this->YThickness_)
            {
              this->YThickness_.set (YThickness_traits::create (i, f, this));
              continue;
            }
          }

          // Height
          //
          if (n.name () == "Height" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            if (!this->Height_)
            {
              this->Height_.set (Height_traits::create (i, f, this));
              continue;
            }
          }

          // BaseElevation
          //
          if (n.name () == "BaseElevation" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            if (!this->BaseElevation_)
            {
              this->BaseElevation_.set (BaseElevation_traits::create (i, f, this));
              continue;
            }
          }

          // DegreeOfNormal
          //
          if (n.name () == "DegreeOfNormal" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            if (!this->DegreeOfNormal_)
            {
              this->DegreeOfNormal_.set (DegreeOfNormal_traits::create (i, f, this));
              continue;
            }
          }

          // ProfilePath
          //
          if (n.name () == "ProfilePath" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< ProfilePath_type > r (
              ProfilePath_traits::create (i, f, this));

            if (!this->ProfilePath_)
            {
              this->ProfilePath_.set (r);
              continue;
            }
          }

          break;
        }
      }

      SimColumnParams* SimColumnParams::
      _clone (::xml_schema::flags f,
              ::xml_schema::container* c) const
      {
        return new class SimColumnParams (*this, f, c);
      }

      SimColumnParams& SimColumnParams::
      operator= (const SimColumnParams& x)
      {
        if (this != &x)
        {
          static_cast< ::namespaces::Sim::ResourcesGeneral::SimBldgModelParams& > (*this) = x;
          this->XThickness_ = x.XThickness_;
          this->YThickness_ = x.YThickness_;
          this->Height_ = x.Height_;
          this->BaseElevation_ = x.BaseElevation_;
          this->DegreeOfNormal_ = x.DegreeOfNormal_;
          this->ProfilePath_ = x.ProfilePath_;
        }

        return *this;
      }

      SimColumnParams::
      ~SimColumnParams ()
      {
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

