// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SimExtendedMaterialProps.hxx"

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
      // SimExtendedMaterialProps
      // 

      const SimExtendedMaterialProps::GlobalId_optional& SimExtendedMaterialProps::
      GlobalId () const
      {
        return this->GlobalId_;
      }

      SimExtendedMaterialProps::GlobalId_optional& SimExtendedMaterialProps::
      GlobalId ()
      {
        return this->GlobalId_;
      }

      void SimExtendedMaterialProps::
      GlobalId (const GlobalId_type& x)
      {
        this->GlobalId_.set (x);
      }

      void SimExtendedMaterialProps::
      GlobalId (const GlobalId_optional& x)
      {
        this->GlobalId_ = x;
      }

      void SimExtendedMaterialProps::
      GlobalId (::std::auto_ptr< GlobalId_type > x)
      {
        this->GlobalId_.set (x);
      }

      const SimExtendedMaterialProps::OwnerHistory_optional& SimExtendedMaterialProps::
      OwnerHistory () const
      {
        return this->OwnerHistory_;
      }

      SimExtendedMaterialProps::OwnerHistory_optional& SimExtendedMaterialProps::
      OwnerHistory ()
      {
        return this->OwnerHistory_;
      }

      void SimExtendedMaterialProps::
      OwnerHistory (const OwnerHistory_type& x)
      {
        this->OwnerHistory_.set (x);
      }

      void SimExtendedMaterialProps::
      OwnerHistory (const OwnerHistory_optional& x)
      {
        this->OwnerHistory_ = x;
      }

      void SimExtendedMaterialProps::
      OwnerHistory (::std::auto_ptr< OwnerHistory_type > x)
      {
        this->OwnerHistory_.set (x);
      }

      const SimExtendedMaterialProps::Material_optional& SimExtendedMaterialProps::
      Material () const
      {
        return this->Material_;
      }

      SimExtendedMaterialProps::Material_optional& SimExtendedMaterialProps::
      Material ()
      {
        return this->Material_;
      }

      void SimExtendedMaterialProps::
      Material (const Material_type& x)
      {
        this->Material_.set (x);
      }

      void SimExtendedMaterialProps::
      Material (const Material_optional& x)
      {
        this->Material_ = x;
      }

      void SimExtendedMaterialProps::
      Material (::std::auto_ptr< Material_type > x)
      {
        this->Material_.set (x);
      }

      const SimExtendedMaterialProps::ExtendedProperties_optional& SimExtendedMaterialProps::
      ExtendedProperties () const
      {
        return this->ExtendedProperties_;
      }

      SimExtendedMaterialProps::ExtendedProperties_optional& SimExtendedMaterialProps::
      ExtendedProperties ()
      {
        return this->ExtendedProperties_;
      }

      void SimExtendedMaterialProps::
      ExtendedProperties (const ExtendedProperties_type& x)
      {
        this->ExtendedProperties_.set (x);
      }

      void SimExtendedMaterialProps::
      ExtendedProperties (const ExtendedProperties_optional& x)
      {
        this->ExtendedProperties_ = x;
      }

      void SimExtendedMaterialProps::
      ExtendedProperties (::std::auto_ptr< ExtendedProperties_type > x)
      {
        this->ExtendedProperties_.set (x);
      }

      const SimExtendedMaterialProps::Name_optional& SimExtendedMaterialProps::
      Name () const
      {
        return this->Name_;
      }

      SimExtendedMaterialProps::Name_optional& SimExtendedMaterialProps::
      Name ()
      {
        return this->Name_;
      }

      void SimExtendedMaterialProps::
      Name (const Name_type& x)
      {
        this->Name_.set (x);
      }

      void SimExtendedMaterialProps::
      Name (const Name_optional& x)
      {
        this->Name_ = x;
      }

      void SimExtendedMaterialProps::
      Name (::std::auto_ptr< Name_type > x)
      {
        this->Name_.set (x);
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
      // SimExtendedMaterialProps
      //

      SimExtendedMaterialProps::
      SimExtendedMaterialProps (const RefId_type& RefId)
      : ::namespaces::Sim::ResourcesGeneral::SimPropertySetDefinition (RefId),
        GlobalId_ (this),
        OwnerHistory_ (this),
        Material_ (this),
        ExtendedProperties_ (this),
        Name_ (this)
      {
      }

      SimExtendedMaterialProps::
      SimExtendedMaterialProps (const SimExtendedMaterialProps& x,
                                ::xml_schema::flags f,
                                ::xml_schema::container* c)
      : ::namespaces::Sim::ResourcesGeneral::SimPropertySetDefinition (x, f, c),
        GlobalId_ (x.GlobalId_, f, this),
        OwnerHistory_ (x.OwnerHistory_, f, this),
        Material_ (x.Material_, f, this),
        ExtendedProperties_ (x.ExtendedProperties_, f, this),
        Name_ (x.Name_, f, this)
      {
      }

      SimExtendedMaterialProps::
      SimExtendedMaterialProps (const ::xercesc::DOMElement& e,
                                ::xml_schema::flags f,
                                ::xml_schema::container* c)
      : ::namespaces::Sim::ResourcesGeneral::SimPropertySetDefinition (e, f | ::xml_schema::flags::base, c),
        GlobalId_ (this),
        OwnerHistory_ (this),
        Material_ (this),
        ExtendedProperties_ (this),
        Name_ (this)
      {
        if ((f & ::xml_schema::flags::base) == 0)
        {
          ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
          this->parse (p, f);
        }
      }

      void SimExtendedMaterialProps::
      parse (::xsd::cxx::xml::dom::parser< char >& p,
             ::xml_schema::flags f)
      {
        this->::namespaces::Sim::ResourcesGeneral::SimPropertySetDefinition::parse (p, f);

        for (; p.more_content (); p.next_content (false))
        {
          const ::xercesc::DOMElement& i (p.cur_element ());
          const ::xsd::cxx::xml::qualified_name< char > n (
            ::xsd::cxx::xml::dom::name< char > (i));

          // GlobalId
          //
          if (n.name () == "GlobalId" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< GlobalId_type > r (
              GlobalId_traits::create (i, f, this));

            if (!this->GlobalId_)
            {
              this->GlobalId_.set (r);
              continue;
            }
          }

          // OwnerHistory
          //
          if (n.name () == "OwnerHistory" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< OwnerHistory_type > r (
              OwnerHistory_traits::create (i, f, this));

            if (!this->OwnerHistory_)
            {
              this->OwnerHistory_.set (r);
              continue;
            }
          }

          // Material
          //
          if (n.name () == "Material" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< Material_type > r (
              Material_traits::create (i, f, this));

            if (!this->Material_)
            {
              this->Material_.set (r);
              continue;
            }
          }

          // ExtendedProperties
          //
          if (n.name () == "ExtendedProperties" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< ExtendedProperties_type > r (
              ExtendedProperties_traits::create (i, f, this));

            if (!this->ExtendedProperties_)
            {
              this->ExtendedProperties_.set (r);
              continue;
            }
          }

          // Name
          //
          if (n.name () == "Name" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< Name_type > r (
              Name_traits::create (i, f, this));

            if (!this->Name_)
            {
              this->Name_.set (r);
              continue;
            }
          }

          break;
        }
      }

      SimExtendedMaterialProps* SimExtendedMaterialProps::
      _clone (::xml_schema::flags f,
              ::xml_schema::container* c) const
      {
        return new class SimExtendedMaterialProps (*this, f, c);
      }

      SimExtendedMaterialProps& SimExtendedMaterialProps::
      operator= (const SimExtendedMaterialProps& x)
      {
        if (this != &x)
        {
          static_cast< ::namespaces::Sim::ResourcesGeneral::SimPropertySetDefinition& > (*this) = x;
          this->GlobalId_ = x.GlobalId_;
          this->OwnerHistory_ = x.OwnerHistory_;
          this->Material_ = x.Material_;
          this->ExtendedProperties_ = x.ExtendedProperties_;
          this->Name_ = x.Name_;
        }

        return *this;
      }

      SimExtendedMaterialProps::
      ~SimExtendedMaterialProps ()
      {
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

