// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SimList_SchemeList_CondenserOperatingScheme.hxx"

#include "simlist_contscheme_1_8_objecttype.hxx"

namespace schema
{
  namespace simxml
  {
    namespace BuildingModel
    {
      // SimList_SchemeList_CondenserOperatingScheme
      // 

      const SimList_SchemeList_CondenserOperatingScheme::SimList_ContScheme_1_8_ObjectType_optional& SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_ObjectType () const
      {
        return this->SimList_ContScheme_1_8_ObjectType_;
      }

      SimList_SchemeList_CondenserOperatingScheme::SimList_ContScheme_1_8_ObjectType_optional& SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_ObjectType ()
      {
        return this->SimList_ContScheme_1_8_ObjectType_;
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_ObjectType (const SimList_ContScheme_1_8_ObjectType_type& x)
      {
        this->SimList_ContScheme_1_8_ObjectType_.set (x);
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_ObjectType (const SimList_ContScheme_1_8_ObjectType_optional& x)
      {
        this->SimList_ContScheme_1_8_ObjectType_ = x;
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_ObjectType (::std::auto_ptr< SimList_ContScheme_1_8_ObjectType_type > x)
      {
        this->SimList_ContScheme_1_8_ObjectType_.set (x);
      }

      const SimList_SchemeList_CondenserOperatingScheme::SimList_ContScheme_1_8_Name_optional& SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_Name () const
      {
        return this->SimList_ContScheme_1_8_Name_;
      }

      SimList_SchemeList_CondenserOperatingScheme::SimList_ContScheme_1_8_Name_optional& SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_Name ()
      {
        return this->SimList_ContScheme_1_8_Name_;
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_Name (const SimList_ContScheme_1_8_Name_type& x)
      {
        this->SimList_ContScheme_1_8_Name_.set (x);
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_Name (const SimList_ContScheme_1_8_Name_optional& x)
      {
        this->SimList_ContScheme_1_8_Name_ = x;
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_Name (::std::auto_ptr< SimList_ContScheme_1_8_Name_type > x)
      {
        this->SimList_ContScheme_1_8_Name_.set (x);
      }

      const SimList_SchemeList_CondenserOperatingScheme::SimList_ContScheme_1_8_SchedName_optional& SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_SchedName () const
      {
        return this->SimList_ContScheme_1_8_SchedName_;
      }

      SimList_SchemeList_CondenserOperatingScheme::SimList_ContScheme_1_8_SchedName_optional& SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_SchedName ()
      {
        return this->SimList_ContScheme_1_8_SchedName_;
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_SchedName (const SimList_ContScheme_1_8_SchedName_type& x)
      {
        this->SimList_ContScheme_1_8_SchedName_.set (x);
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_SchedName (const SimList_ContScheme_1_8_SchedName_optional& x)
      {
        this->SimList_ContScheme_1_8_SchedName_ = x;
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      SimList_ContScheme_1_8_SchedName (::std::auto_ptr< SimList_ContScheme_1_8_SchedName_type > x)
      {
        this->SimList_ContScheme_1_8_SchedName_.set (x);
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace schema
{
  namespace simxml
  {
    namespace BuildingModel
    {
      // SimList_SchemeList_CondenserOperatingScheme
      //

      SimList_SchemeList_CondenserOperatingScheme::
      SimList_SchemeList_CondenserOperatingScheme ()
      : ::schema::simxml::BuildingModel::SimList_SchemeList (),
        SimList_ContScheme_1_8_ObjectType_ (this),
        SimList_ContScheme_1_8_Name_ (this),
        SimList_ContScheme_1_8_SchedName_ (this)
      {
      }

      SimList_SchemeList_CondenserOperatingScheme::
      SimList_SchemeList_CondenserOperatingScheme (const RefId_type& RefId)
      : ::schema::simxml::BuildingModel::SimList_SchemeList (RefId),
        SimList_ContScheme_1_8_ObjectType_ (this),
        SimList_ContScheme_1_8_Name_ (this),
        SimList_ContScheme_1_8_SchedName_ (this)
      {
      }

      SimList_SchemeList_CondenserOperatingScheme::
      SimList_SchemeList_CondenserOperatingScheme (const SimList_SchemeList_CondenserOperatingScheme& x,
                                                   ::xml_schema::flags f,
                                                   ::xml_schema::container* c)
      : ::schema::simxml::BuildingModel::SimList_SchemeList (x, f, c),
        SimList_ContScheme_1_8_ObjectType_ (x.SimList_ContScheme_1_8_ObjectType_, f, this),
        SimList_ContScheme_1_8_Name_ (x.SimList_ContScheme_1_8_Name_, f, this),
        SimList_ContScheme_1_8_SchedName_ (x.SimList_ContScheme_1_8_SchedName_, f, this)
      {
      }

      SimList_SchemeList_CondenserOperatingScheme::
      SimList_SchemeList_CondenserOperatingScheme (const ::xercesc::DOMElement& e,
                                                   ::xml_schema::flags f,
                                                   ::xml_schema::container* c)
      : ::schema::simxml::BuildingModel::SimList_SchemeList (e, f | ::xml_schema::flags::base, c),
        SimList_ContScheme_1_8_ObjectType_ (this),
        SimList_ContScheme_1_8_Name_ (this),
        SimList_ContScheme_1_8_SchedName_ (this)
      {
        if ((f & ::xml_schema::flags::base) == 0)
        {
          ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
          this->parse (p, f);
        }
      }

      void SimList_SchemeList_CondenserOperatingScheme::
      parse (::xsd::cxx::xml::dom::parser< char >& p,
             ::xml_schema::flags f)
      {
        this->::schema::simxml::BuildingModel::SimList_SchemeList::parse (p, f);

        for (; p.more_content (); p.next_content (false))
        {
          const ::xercesc::DOMElement& i (p.cur_element ());
          const ::xsd::cxx::xml::qualified_name< char > n (
            ::xsd::cxx::xml::dom::name< char > (i));

          // SimList_ContScheme_1_8_ObjectType
          //
          if (n.name () == "SimList_ContScheme_1_8_ObjectType" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/BuildingModel")
          {
            ::std::auto_ptr< SimList_ContScheme_1_8_ObjectType_type > r (
              SimList_ContScheme_1_8_ObjectType_traits::create (i, f, this));

            if (!this->SimList_ContScheme_1_8_ObjectType_)
            {
              this->SimList_ContScheme_1_8_ObjectType_.set (r);
              continue;
            }
          }

          // SimList_ContScheme_1_8_Name
          //
          if (n.name () == "SimList_ContScheme_1_8_Name" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/BuildingModel")
          {
            ::std::auto_ptr< SimList_ContScheme_1_8_Name_type > r (
              SimList_ContScheme_1_8_Name_traits::create (i, f, this));

            if (!this->SimList_ContScheme_1_8_Name_)
            {
              this->SimList_ContScheme_1_8_Name_.set (r);
              continue;
            }
          }

          // SimList_ContScheme_1_8_SchedName
          //
          if (n.name () == "SimList_ContScheme_1_8_SchedName" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/BuildingModel")
          {
            ::std::auto_ptr< SimList_ContScheme_1_8_SchedName_type > r (
              SimList_ContScheme_1_8_SchedName_traits::create (i, f, this));

            if (!this->SimList_ContScheme_1_8_SchedName_)
            {
              this->SimList_ContScheme_1_8_SchedName_.set (r);
              continue;
            }
          }

          break;
        }
      }

      SimList_SchemeList_CondenserOperatingScheme* SimList_SchemeList_CondenserOperatingScheme::
      _clone (::xml_schema::flags f,
              ::xml_schema::container* c) const
      {
        return new class SimList_SchemeList_CondenserOperatingScheme (*this, f, c);
      }

      SimList_SchemeList_CondenserOperatingScheme& SimList_SchemeList_CondenserOperatingScheme::
      operator= (const SimList_SchemeList_CondenserOperatingScheme& x)
      {
        if (this != &x)
        {
          static_cast< ::schema::simxml::BuildingModel::SimList_SchemeList& > (*this) = x;
          this->SimList_ContScheme_1_8_ObjectType_ = x.SimList_ContScheme_1_8_ObjectType_;
          this->SimList_ContScheme_1_8_Name_ = x.SimList_ContScheme_1_8_Name_;
          this->SimList_ContScheme_1_8_SchedName_ = x.SimList_ContScheme_1_8_SchedName_;
        }

        return *this;
      }

      SimList_SchemeList_CondenserOperatingScheme::
      ~SimList_SchemeList_CondenserOperatingScheme ()
      {
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace schema
{
  namespace simxml
  {
    namespace BuildingModel
    {
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

