// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SimGeomSurface_BoundedSurface_RectangularTrimmedSurface.hxx"

namespace schema
{
  namespace simxml
  {
    namespace ResourcesGeometry
    {
      // SimGeomSurface_BoundedSurface_RectangularTrimmedSurface
      // 

      const SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::BasisSurface_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      BasisSurface () const
      {
        return this->BasisSurface_;
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::BasisSurface_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      BasisSurface ()
      {
        return this->BasisSurface_;
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      BasisSurface (const BasisSurface_type& x)
      {
        this->BasisSurface_.set (x);
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      BasisSurface (const BasisSurface_optional& x)
      {
        this->BasisSurface_ = x;
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      BasisSurface (::std::auto_ptr< BasisSurface_type > x)
      {
        this->BasisSurface_.set (x);
      }

      const SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::U1_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      U1 () const
      {
        return this->U1_;
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::U1_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      U1 ()
      {
        return this->U1_;
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      U1 (const U1_type& x)
      {
        this->U1_.set (x);
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      U1 (const U1_optional& x)
      {
        this->U1_ = x;
      }

      const SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::V1_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      V1 () const
      {
        return this->V1_;
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::V1_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      V1 ()
      {
        return this->V1_;
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      V1 (const V1_type& x)
      {
        this->V1_.set (x);
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      V1 (const V1_optional& x)
      {
        this->V1_ = x;
      }

      const SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::U2_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      U2 () const
      {
        return this->U2_;
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::U2_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      U2 ()
      {
        return this->U2_;
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      U2 (const U2_type& x)
      {
        this->U2_.set (x);
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      U2 (const U2_optional& x)
      {
        this->U2_ = x;
      }

      const SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::V2_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      V2 () const
      {
        return this->V2_;
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::V2_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      V2 ()
      {
        return this->V2_;
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      V2 (const V2_type& x)
      {
        this->V2_.set (x);
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      V2 (const V2_optional& x)
      {
        this->V2_ = x;
      }

      const SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::Usense_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      Usense () const
      {
        return this->Usense_;
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::Usense_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      Usense ()
      {
        return this->Usense_;
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      Usense (const Usense_type& x)
      {
        this->Usense_.set (x);
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      Usense (const Usense_optional& x)
      {
        this->Usense_ = x;
      }

      const SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::Vsense_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      Vsense () const
      {
        return this->Vsense_;
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::Vsense_optional& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      Vsense ()
      {
        return this->Vsense_;
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      Vsense (const Vsense_type& x)
      {
        this->Vsense_.set (x);
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      Vsense (const Vsense_optional& x)
      {
        this->Vsense_ = x;
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace schema
{
  namespace simxml
  {
    namespace ResourcesGeometry
    {
      // SimGeomSurface_BoundedSurface_RectangularTrimmedSurface
      //

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface ()
      : ::schema::simxml::ResourcesGeometry::SimGeomSurface_BoundedSurface (),
        BasisSurface_ (this),
        U1_ (this),
        V1_ (this),
        U2_ (this),
        V2_ (this),
        Usense_ (this),
        Vsense_ (this)
      {
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface (const RefId_type& RefId)
      : ::schema::simxml::ResourcesGeometry::SimGeomSurface_BoundedSurface (RefId),
        BasisSurface_ (this),
        U1_ (this),
        V1_ (this),
        U2_ (this),
        V2_ (this),
        Usense_ (this),
        Vsense_ (this)
      {
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface (const SimGeomSurface_BoundedSurface_RectangularTrimmedSurface& x,
                                                               ::xml_schema::flags f,
                                                               ::xml_schema::container* c)
      : ::schema::simxml::ResourcesGeometry::SimGeomSurface_BoundedSurface (x, f, c),
        BasisSurface_ (x.BasisSurface_, f, this),
        U1_ (x.U1_, f, this),
        V1_ (x.V1_, f, this),
        U2_ (x.U2_, f, this),
        V2_ (x.V2_, f, this),
        Usense_ (x.Usense_, f, this),
        Vsense_ (x.Vsense_, f, this)
      {
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface (const ::xercesc::DOMElement& e,
                                                               ::xml_schema::flags f,
                                                               ::xml_schema::container* c)
      : ::schema::simxml::ResourcesGeometry::SimGeomSurface_BoundedSurface (e, f | ::xml_schema::flags::base, c),
        BasisSurface_ (this),
        U1_ (this),
        V1_ (this),
        U2_ (this),
        V2_ (this),
        Usense_ (this),
        Vsense_ (this)
      {
        if ((f & ::xml_schema::flags::base) == 0)
        {
          ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
          this->parse (p, f);
        }
      }

      void SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      parse (::xsd::cxx::xml::dom::parser< char >& p,
             ::xml_schema::flags f)
      {
        this->::schema::simxml::ResourcesGeometry::SimGeomSurface_BoundedSurface::parse (p, f);

        for (; p.more_content (); p.next_content (false))
        {
          const ::xercesc::DOMElement& i (p.cur_element ());
          const ::xsd::cxx::xml::qualified_name< char > n (
            ::xsd::cxx::xml::dom::name< char > (i));

          // BasisSurface
          //
          if (n.name () == "BasisSurface" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            ::std::auto_ptr< BasisSurface_type > r (
              BasisSurface_traits::create (i, f, this));

            if (!this->BasisSurface_)
            {
              this->BasisSurface_.set (r);
              continue;
            }
          }

          // U1
          //
          if (n.name () == "U1" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            if (!this->U1_)
            {
              this->U1_.set (U1_traits::create (i, f, this));
              continue;
            }
          }

          // V1
          //
          if (n.name () == "V1" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            if (!this->V1_)
            {
              this->V1_.set (V1_traits::create (i, f, this));
              continue;
            }
          }

          // U2
          //
          if (n.name () == "U2" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            if (!this->U2_)
            {
              this->U2_.set (U2_traits::create (i, f, this));
              continue;
            }
          }

          // V2
          //
          if (n.name () == "V2" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            if (!this->V2_)
            {
              this->V2_.set (V2_traits::create (i, f, this));
              continue;
            }
          }

          // Usense
          //
          if (n.name () == "Usense" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            if (!this->Usense_)
            {
              this->Usense_.set (Usense_traits::create (i, f, this));
              continue;
            }
          }

          // Vsense
          //
          if (n.name () == "Vsense" && n.namespace_ () == "http://d-alchemy.com/schema/simxml/ResourcesGeometry")
          {
            if (!this->Vsense_)
            {
              this->Vsense_.set (Vsense_traits::create (i, f, this));
              continue;
            }
          }

          break;
        }
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface* SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      _clone (::xml_schema::flags f,
              ::xml_schema::container* c) const
      {
        return new class SimGeomSurface_BoundedSurface_RectangularTrimmedSurface (*this, f, c);
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface& SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      operator= (const SimGeomSurface_BoundedSurface_RectangularTrimmedSurface& x)
      {
        if (this != &x)
        {
          static_cast< ::schema::simxml::ResourcesGeometry::SimGeomSurface_BoundedSurface& > (*this) = x;
          this->BasisSurface_ = x.BasisSurface_;
          this->U1_ = x.U1_;
          this->V1_ = x.V1_;
          this->U2_ = x.U2_;
          this->V2_ = x.V2_;
          this->Usense_ = x.Usense_;
          this->Vsense_ = x.Vsense_;
        }

        return *this;
      }

      SimGeomSurface_BoundedSurface_RectangularTrimmedSurface::
      ~SimGeomSurface_BoundedSurface_RectangularTrimmedSurface ()
      {
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace schema
{
  namespace simxml
  {
    namespace ResourcesGeometry
    {
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

