// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "SimTimeSeriesSchedule_Week_Compact.hxx"

#include "simtimeseriessched_daytype_1_5.hxx"

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
      // SimTimeSeriesSchedule_Week_Compact
      // 

      const SimTimeSeriesSchedule_Week_Compact::SimTimeSeriesSched_DayType_1_5_optional& SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_DayType_1_5 () const
      {
        return this->SimTimeSeriesSched_DayType_1_5_;
      }

      SimTimeSeriesSchedule_Week_Compact::SimTimeSeriesSched_DayType_1_5_optional& SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_DayType_1_5 ()
      {
        return this->SimTimeSeriesSched_DayType_1_5_;
      }

      void SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_DayType_1_5 (const SimTimeSeriesSched_DayType_1_5_type& x)
      {
        this->SimTimeSeriesSched_DayType_1_5_.set (x);
      }

      void SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_DayType_1_5 (const SimTimeSeriesSched_DayType_1_5_optional& x)
      {
        this->SimTimeSeriesSched_DayType_1_5_ = x;
      }

      void SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_DayType_1_5 (::std::auto_ptr< SimTimeSeriesSched_DayType_1_5_type > x)
      {
        this->SimTimeSeriesSched_DayType_1_5_.set (x);
      }

      const SimTimeSeriesSchedule_Week_Compact::SimTimeSeriesSched_Sched_DayName_1_5_optional& SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_Sched_DayName_1_5 () const
      {
        return this->SimTimeSeriesSched_Sched_DayName_1_5_;
      }

      SimTimeSeriesSchedule_Week_Compact::SimTimeSeriesSched_Sched_DayName_1_5_optional& SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_Sched_DayName_1_5 ()
      {
        return this->SimTimeSeriesSched_Sched_DayName_1_5_;
      }

      void SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_Sched_DayName_1_5 (const SimTimeSeriesSched_Sched_DayName_1_5_type& x)
      {
        this->SimTimeSeriesSched_Sched_DayName_1_5_.set (x);
      }

      void SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_Sched_DayName_1_5 (const SimTimeSeriesSched_Sched_DayName_1_5_optional& x)
      {
        this->SimTimeSeriesSched_Sched_DayName_1_5_ = x;
      }

      void SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSched_Sched_DayName_1_5 (::std::auto_ptr< SimTimeSeriesSched_Sched_DayName_1_5_type > x)
      {
        this->SimTimeSeriesSched_Sched_DayName_1_5_.set (x);
      }
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
      // SimTimeSeriesSchedule_Week_Compact
      //

      SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSchedule_Week_Compact (const RefId_type& RefId)
      : ::namespaces::Sim::ResourcesGeneral::SimTimeSeriesSchedule_Week (RefId),
        SimTimeSeriesSched_DayType_1_5_ (this),
        SimTimeSeriesSched_Sched_DayName_1_5_ (this)
      {
      }

      SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSchedule_Week_Compact (const SimTimeSeriesSchedule_Week_Compact& x,
                                          ::xml_schema::flags f,
                                          ::xml_schema::container* c)
      : ::namespaces::Sim::ResourcesGeneral::SimTimeSeriesSchedule_Week (x, f, c),
        SimTimeSeriesSched_DayType_1_5_ (x.SimTimeSeriesSched_DayType_1_5_, f, this),
        SimTimeSeriesSched_Sched_DayName_1_5_ (x.SimTimeSeriesSched_Sched_DayName_1_5_, f, this)
      {
      }

      SimTimeSeriesSchedule_Week_Compact::
      SimTimeSeriesSchedule_Week_Compact (const ::xercesc::DOMElement& e,
                                          ::xml_schema::flags f,
                                          ::xml_schema::container* c)
      : ::namespaces::Sim::ResourcesGeneral::SimTimeSeriesSchedule_Week (e, f | ::xml_schema::flags::base, c),
        SimTimeSeriesSched_DayType_1_5_ (this),
        SimTimeSeriesSched_Sched_DayName_1_5_ (this)
      {
        if ((f & ::xml_schema::flags::base) == 0)
        {
          ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
          this->parse (p, f);
        }
      }

      void SimTimeSeriesSchedule_Week_Compact::
      parse (::xsd::cxx::xml::dom::parser< char >& p,
             ::xml_schema::flags f)
      {
        this->::namespaces::Sim::ResourcesGeneral::SimTimeSeriesSchedule_Week::parse (p, f);

        for (; p.more_content (); p.next_content (false))
        {
          const ::xercesc::DOMElement& i (p.cur_element ());
          const ::xsd::cxx::xml::qualified_name< char > n (
            ::xsd::cxx::xml::dom::name< char > (i));

          // SimTimeSeriesSched_DayType_1_5
          //
          if (n.name () == "SimTimeSeriesSched_DayType_1_5" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< SimTimeSeriesSched_DayType_1_5_type > r (
              SimTimeSeriesSched_DayType_1_5_traits::create (i, f, this));

            if (!this->SimTimeSeriesSched_DayType_1_5_)
            {
              this->SimTimeSeriesSched_DayType_1_5_.set (r);
              continue;
            }
          }

          // SimTimeSeriesSched_Sched_DayName_1_5
          //
          if (n.name () == "SimTimeSeriesSched_Sched_DayName_1_5" && n.namespace_ () == "http://www.lbl.gov/namespaces/Sim/ResourcesGeneral")
          {
            ::std::auto_ptr< SimTimeSeriesSched_Sched_DayName_1_5_type > r (
              SimTimeSeriesSched_Sched_DayName_1_5_traits::create (i, f, this));

            if (!this->SimTimeSeriesSched_Sched_DayName_1_5_)
            {
              this->SimTimeSeriesSched_Sched_DayName_1_5_.set (r);
              continue;
            }
          }

          break;
        }
      }

      SimTimeSeriesSchedule_Week_Compact* SimTimeSeriesSchedule_Week_Compact::
      _clone (::xml_schema::flags f,
              ::xml_schema::container* c) const
      {
        return new class SimTimeSeriesSchedule_Week_Compact (*this, f, c);
      }

      SimTimeSeriesSchedule_Week_Compact& SimTimeSeriesSchedule_Week_Compact::
      operator= (const SimTimeSeriesSchedule_Week_Compact& x)
      {
        if (this != &x)
        {
          static_cast< ::namespaces::Sim::ResourcesGeneral::SimTimeSeriesSchedule_Week& > (*this) = x;
          this->SimTimeSeriesSched_DayType_1_5_ = x.SimTimeSeriesSched_DayType_1_5_;
          this->SimTimeSeriesSched_Sched_DayName_1_5_ = x.SimTimeSeriesSched_Sched_DayName_1_5_;
        }

        return *this;
      }

      SimTimeSeriesSchedule_Week_Compact::
      ~SimTimeSeriesSchedule_Week_Compact ()
      {
      }
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace namespaces
{
  namespace Sim
  {
    namespace ResourcesGeneral
    {
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

